### PR TITLE
Cristian dev

### PR DESCRIPTION
**Pull request by dipietrantonio**
1. Parametrizes the whole installation directory within the Spack yaml files (as opposed to the DATE_TAG parameter). This allows for testing of the scripts on a local directory.
2. Removes output redirection to logfiles in several parts of the installation process. All output is sent to stdout/stderr. Redirection can be used "at the top level", when running the installation script. It is better to have 1/2 files instead of keeping track of several log files in several locations (in my opinion).
3. Adds the `install_software_stack.sh` script to perform the software stack installation.

### CODE REVIEW

**Comment by dipietrantonio** [comment]
There is still work to do to make this looks nice and ready for production, but I would like to start a discussion around the changes.

**Comment by marcodelapierre** [comment]
Haven't looked at the implementation, just the summary.

I like point 1. a lot!
Agree on point 3.

Point 2. : not sure what outputs are affected.
The requirement I think it is important to try and comply with is the ability to log Spack installations of the various packages, so that we are able to later have a look at them. In doing that, it would also be good to categorise outputs according to some criterion, so as to have a filesystem hierarchy for the logs, for a few reasons:
* being able to browse them in a friendly way
* reducing the chance of data loss (lose 1 file -> you don't lose all logs)
* enabling parallel Spack installations of packages, without conflicts in writing outputs to the same file.

Lots of words, sorry! :-D
What do you think @dipietrantonio ?

**Comment by dipietrantonio** [comment]
Hi Marco, thanks for your review, I appreciate the fact you spend time to carefully express and motivate your ideas.

On the long term, I believe setting up a more advanced log system is necessary for the reasons you pointed out. The fact is that Deva & I had to get up to speed with this complex set of scripts rather quickly and seeing its output in one place, in a sequential way, helped us to locate issues in the manner we were executing the scripts and correct them, as well as testing our improvements. For instance, not separating the error log from the standard output gave errors the context of where they happened.

I would prefer to keep the changes so we can debug faster the software stack installation. Once we are more comfortable with it, we can set up again the previous (or a new one) log system. I am keen to hear opinions from @ddeeptimahanti and @pelahi

**Comment by dipietrantonio** [comment]
I have addressed all the outstanding issues and I have tested them on Joey. Everything is working fine.

**Comment by marcodelapierre** [comment]
Thank you Cristian, always good to have these conversations to share perspectives!
What you say makes complete sense to me, in the end the functionalities of this setup need to work for those who deploy the software, in this case primarily you, Deva and Pascal! :-)
I certainly also support noting down a "mid future to-do" for a more articulated logging feature.

**Comment by marcodelapierre** [comment]
Great job!

**Review by pelahi — APPROVED** [review]

**Comment by marcodelapierre** [comment]
@dipietrantonio I had one more thought around the re-parametrisation of the installation, DATE_TAG, and so on; note that I have not looked into your implementation, I am only thinking at a conceptual level.

When working on these configurations, make sure the setup can accommodate multiple stacks at once (e.g. 2022.05, 2022.11, and so on), in terms of both enabling a correct installation (in the right paths) and allowing usage (of a given dated stack). It is good to test these as well: `which` spack is in use? where does a package gets installed? `which` end user package gets used?
For instance, the previous Spack installation script was generating two modulefiles:
- one using the `current` path symlink, for end users
- one using the date_tag path, for internal use on a specific stack

**Pull request merged**
