### PR TITLE
Removes the Topaz system.

### PR DESCRIPTION
**Pull request by dipietrantonio**
Should we remove the other non-setonix systems as well?

### CODE REVIEW

**Review by pelahi — COMMENTED** [review]
My suggestion is to move these systems to systems/deprecated/ for now and then removal. Thoughts?

**Comment by marcodelapierre** [comment]
On my side I think it is equivalent, the files are stored in the git history anyway .. please folks do proceed as you deem most appropriate

**Comment by dipietrantonio** [comment]
Yes I would just remove everything except setonix, If we need askapingest or garrawarla (unlikely) we can bring them back. Also, those environments are so out of date that would need to be rewritten anyway.

**Review by ddeeptimahanti — APPROVED** [review]
RIP Topaz!

**Review by pelahi — APPROVED** [review]

**Pull request merged**
