### PR TITLE
Compiler update for gpu

### PR DESCRIPTION
**Pull request by pelahi**
The update would ensure that codes are correctly compiled with the additional flags for gpus. However, this does mean that they would sit in the gcc/12.0.0gpu/ directory rather than gcc/12.0.0/ directory. I think it would just be a matter of a post-processing script to move all of these from the `<compiler>@<version>gpu` to the standard `<compiler>@<version>` directories. Thoughts?

### CODE REVIEW

**Comment by dipietrantonio** [comment]
Hi Pascal, would you merge this into `joey-cpe23.03` instead of main? We should keep working on `joey-cpe23.03` until deployment happens. It also makes it easier to see what changes were introduced by your commits, given that this branch is based on `joey-cpe23.03`

**Comment by dipietrantonio** [comment]
> The update would ensure that codes are correctly compiled with the additional flags for gpus.

Not all codes need to be compiled with these compilers though, right? Is there something in our current software stack that need these flags? Also, should not Spack be aware of the Cray Compiler wrappers? Are these flags not normally included with the Cray wrappers?

**Comment by marcodelapierre** [comment]
@pelahi  please double check rocm version in compilers.yaml (5.2.3 vs 5.4.3)

**Comment by dipietrantonio** [comment]
> @pelahi please double check rocm version in compilers.yaml (5.2.3 vs 5.4.3)

@marcodelapierre The new CPE comes with `rocm/5.2.3` and we decided to build the software stack with the Cray provided ROCm instead of the one I built, at least until we have more confidence in it.

**Comment by dipietrantonio** [comment]
Also apparently there are many performance regressions in 5.4 and 5.5 (in `rocfft` for instance, as I have heard from users), so it is not too bad in the end.

**Comment by pelahi** [comment]
Just to be clear, the flags are not provided by the compiler wrappers, specifically the MPI GPU-GPU library. So that needs to be added and the easiest way to add it is to have a specific compiler with the flags set as well as the environmental flag.

**Comment by ddeeptimahanti** [comment]
@dipietrantonio - we don't need to compile everything with this. We can define a new matrix for just gpu packages and use this compiler.

**Review by ddeeptimahanti — APPROVED** [review]
This has changes from PR-185 as well

**Review by dipietrantonio — APPROVED** [review]

**Pull request merged**
