### PR TITLE
Update/spack module defaults

### PR DESCRIPTION
**Pull request by marcodelapierre**
The Lmod function I had found, requireFullName(), is only in newer Lmod versions, not in Joey.
But I had a look into the source, and it was super easy to embed the functionality in our Lua template:

```
if (mode() == "load") then
  if (myModuleUsrName() ~= myModuleFullName()) then
    LmodError("You must load this module as <name>/<version>.")
  end
end
```

This can replace the module naming `<tool>/<ver>/module`, so that we go back to just `<tool>/<ver>`;
the advantage is a cleaner output for "module avail" and similar, while still enforcing versions.
Another advantage (I think), is that we may be able to use again some Spack functionality for naming modules, specifically all `suffix` related naming functionalities.

Key question, do you like this error message:
```
You must load this module as <name>/<version>.
```

Or can you think of a nicer one?

Thanks

### CODE REVIEW

**Review by pelahi — APPROVED** [review]
Looks good to me

**Comment by dipietrantonio** [comment]
Hi Marco,
sorry for the late review. This looks good to me, and I want to point out that we could add the above code in a load hook (a function called every time a `module load` is executed, within the SitePackage.lua file, in the lua installation folder. It is the same file where I have implemented Lmod logging.

Check it out here: https://bitbucket.pawsey.org.au/users/cdipietrantonio/repos/modules-logging/browse/lmod/SitePackage.lua 

Now, since you add this code in a module template in Spack, I say your solution is good. But what about modules built via other means? for instance, maali or manual build? We risk to forget adding the above bit of code in the module. If we add such code in the SitePackage.lua file, then it is enforced for every module.

Cheers
Cristian

**Comment by marcodelapierre** [comment]
I think yours is a very good idea. Note how, that way, it would apply to Cray modules, too, which is good from my perspective! 🙂 
This makes me think that it would be great if you could test it, though, just in case some of the Cray modules do loading without specifying the version. (which might need some extra coding in the hook, to fix it)

Once tested, maybe you can add in this very repo, somewhere in `setonix/setup` ...?

**Comment by marcodelapierre** [comment]
On this same topic, just a note of a slightly inconsistency that arises when disabling module default versions that way (pointed out by a github collaborator).

When doing `module avail`, you will get a `D` aside of the prescribed default version, even if the corresponding `module load <tool>` will then fail. This is expected, as the version check happens at the time of the `module load`.

I am wondering how confusing this could be to users, but I am afraid right now I can't think of a solution.

**Pull request merged**
