### PR TITLE
Feature/topaz update

### PR DESCRIPTION
**Pull request by pelahi**
Update to topaz, zeus, and magnus/galaxy yamls.

### CODE REVIEW

**Comment by marcodelapierre** [comment]
Hi @pelahi , apologies, I only got to this one today. Is there any specific aspect where you would like feedback for this PR?

**Comment by pelahi** [comment]
Not really. Just wanted to make sure you are happy with the overall edits. There are a lot of new files but most are just small modifications to point to specific paths.

**Review by marcodelapierre — APPROVED** [review]

**Comment by marcodelapierre** [comment]
Thanks for this work Pascal!
The only general comment that I have is around the scope.

For all clusters that will stick around also with Setonix for a while (Topaz, Askap-Ingest?, Garrawarla?), let's define the goal for using Spack, so that we can in turn define a "support level" for users.

My suggested minimal level of goal/support for these clusters would be to use Spack to complement installations on a basis of necessity/convenience, that is, to install packages/applications where Spack is more convenient for whatever reason. In this context, unlike Setonix, we can aim to have a Spack configuration that just "does the job", without spending too much time, for instance, on system externals. Likewise for what regards users, I suggest we do not commit to Spack support for them; they can use it, but we won't help them. The only exception here is probably PaCER/ASKAP/MWA, where we might occasionally need to help them out.
Finally, for these longer-lived clusters, once you're happy with a working configuration, I suggest to move them from the "examples" directory to the root directory of this repo, so they're easier to find, and it's more obvious that these configs are being actively used (we can "archive" them later down the track, when the clusters are retired).

**Comment by pelahi** [comment]
I'll adjust this when I have time, moving stuff from examples.

**Comment by marcodelapierre** [comment]
Sure. Meanwhile, if the current changes are finalised on your end, feel free to merge!

**Pull request merged**
