### PR TITLE
Added Joey configuration

### PR DESCRIPTION
**Pull request by pelahi**
- Added configuration for Joey
- Configuration is set up for Casinni NICs and SS>=11

### CODE REVIEW

**Comment by pelahi** [comment]
I am also going to add some updates to scripts for proper deployment of several different singularity modules

**Comment by dipietrantonio** [comment]
I was wondering whether we should just use the setonix one to avoid duplication. Indeed, Joey should be a replica of setonix (in theory).

**Comment by marcodelapierre** [comment]
On Cristian's suggestion to avoid duplication:

if the differences are indeed minimal so as that they can be coded through environment variables (e.g. install paths), a trick like this can be used:
```
export VARIABLE=${VARIABLE:-"setonix_value"}
```
Then for Setonix nothing is needed:
```
./install_and_have_fun.sh
```
Whereas for Joey the variable value requires a redefinition:
```
export VARIABLE="joey_value"
./install_and_have_fun.sh
```

**Comment by pelahi** [comment]
The main issue with having joey being a mirror of setonix is that currently joey is NOT a mirror of setonix and given the rapid changes scheduled, it might be a while before they are really similar. 

- For instance on joey, libfabric/1.15.2.0 but setonix has libfabric/1.15.0.0

**Comment by pelahi** [comment]
Now ready for full review

**Comment by dipietrantonio** [comment]
This will have to wait until Joey comes back up. You should ensure that any change to the Joey configuration has now to be applied to the one of Setonix, where applicable.  It seems to me that the difference between Joey and Setonix here is reflected only in the singularity modulefile, is this right?

**Comment by dipietrantonio** [comment]
@ddeeptimahanti and I discussed this and we think that at this stage having a separate set of configuration files for Joey creates too much duplication for a relatively small difference (libfabric). We suggest using Setonix config as a start and applying necessary patches using `sed` or `patch`. Note that, in paths, you don't really need to change the "setonix" to "joey" as we can really pretend joey to be setonix. Especially because filesystems are different.

**Comment by dipietrantonio** [comment]
Hi @pelahi, @ddeeptimahanti and I discussed this PR and we think it should be rejected as outdated. The Joey system is also converging towards being very similar to Setonix, so we think it is not worth the effort to maintain a separate system configuration.

However, there might be some changes here that are useful to keep for Setonix, especially about the Singularity module files. Is it the case?

**Pull request closed without merging**
