### PR TITLE
Updating the compiler versions in the configs

### PR DESCRIPTION
**Pull request by pelahi**

### CODE REVIEW

**Comment by pelahi** [comment]
Still requires further updates to packages.yaml based on the versions of packages on setonix.

**Review by marcodelapierre — CHANGES_REQUESTED** [review]
Thanks Pascal!

Just a couple of edits:

1. needed: please bump aocc and cce versions in the only two environments that build something with them, env_python and env_utils;

2. suggested: can you add a gcc "@11.2.0profile" compiler entry, eg with `-O3 -g -pg` ?

**Comment by marcodelapierre** [comment]
One more needed edit request Pascal:

3. can you update the compiler versions inside the file `setonix/setup/variables.sh`? This is used as the source of wisdom by the various setup scripts

**Comment by marcodelapierre** [comment]
Hi have just carefully checked and then merged the latest main commits into this branch

**Comment by marcodelapierre** [comment]
Added 4 edits I requested above:
1. compiler version bump in 2x environments
2. added gcc@11.2.0profile
3. / 4. compiler version bump in 2x setup files

**Comment by marcodelapierre** [comment]
To be checked: for compilers, arch module updated from `rome` to `milan`

Waiting for Lmod on Setonix, to test it

**Comment by marcodelapierre** [comment]
OK, added back the `profile` compiler in compilers.yaml
plus minor edits in the comments

**Pull request merged**
