### PR TITLE
Rename NAMD lpython patch, add explicatory comment.

### PR DESCRIPTION
**Pull request by halfflat**
* Rename lpython patch to clarify it is required to support python 3.8 versions and later (note 3.7 and earlier are now EOL).
* Add comment to recipe to explain.

### CODE REVIEW

**Review by dipietrantonio — APPROVED** [review]

**Comment by dipietrantonio** [comment]
Hi @halfflat , I think you got beaten on time. I think there is the same patch on the `develop` branch of Spack. Take a look at

https://github.com/PawseySC/spack/blob/develop/var/spack/repos/builtin/packages/namd/namd-python38.patch

can you confirm ?

**Comment by halfflat** [comment]
Yep, that patch does the same thing, although the pre-3.8 work around that checks for "Usage" in the output of python3-config is incorrect: the usage error is sent to stderr and is not captured with `$()`.

**Comment by halfflat** [comment]
That said, we got our original patch for the python issue in our repo on 18/12/21 :) #e2766440216d349969ecc4b79827f4fcb52b9624

**Comment by dipietrantonio** [comment]
@halfflat eventually we will merge our changes in their branch. The Cray Shasta support s not there yet, and we can also fix that error you pointed out. Should we name our patch the same as theirs so that we can more easily propose our better patch?

**Comment by halfflat** [comment]
I don't think there's any need to align patch names at this stage; when we're looking to contribute upstream we can split the two items (viz. Shasta support and robust python-config use) into two different PRs, and base the python-config edit on their existing patch.

**Review by ddeeptimahanti — APPROVED** [review]

**Pull request merged**
