### PR TITLE
Introducing use of singularity mpi and nompi modules

### PR DESCRIPTION
**Pull request by marcodelapierre**

### CODE REVIEW

**Comment by marcodelapierre** [comment]
@pelahi can you review?

@dipietrantonio FYI

**Review by pelahi — APPROVED** [review]
Changes look good.

**Comment by marcodelapierre** [comment]
thanks Pascal!

@dipietrantonio can you also review, and merge if approved?

**Comment by dipietrantonio** [comment]
This looks good but I would like to test it before merging.

**Comment by marcodelapierre** [comment]
good to go?

**Comment by dipietrantonio** [comment]
Haven't had the chance to test it on joey since it is now not available. I will run it on Setonix to see how It goes.

**Comment by marcodelapierre** [comment]
How is it going here @dipietrantonio ?

**Review by dipietrantonio — APPROVED** [review]

**Comment by marcodelapierre** [comment]
thanks Cristian!

**Pull request merged**
